version: '3.6'
services:
  mock:
    build:
      context: .
    environment:
      HOST: server
    volumes:
      - "./:/server"
      - "/server/node_modules"
    networks:
      - pi2

networks:
  pi2:
    external: true

