version: '3.6'
services:
  mock:
    build:
      context: .
    environment:
      FTP_HOST: server
    volumes:
      - "./:/server"
      - "/server/node_modules"
    networks:
      - pi2
    ports:
      - "3030:3030"

networks:
  pi2:
    external: true

